export const STATUS_CODE_SUCCESS = 200;
export const STATUS_CODE_CREATED = 201;
export const STATUS_CODE_INCORRECT_PARAMS = 400;
export const STATUS_CODE_ACCOUNT_DOES_NOT_EXIST = 401;
export const STATUS_CODE_WRONG_PASSWORD = 403;
export const STATUS_CODE_CONFLICT = 409;
export const STATUS_CODE_UNEXPECTED_ERROR = 503;
