name: Node CI

on:
  push:
    branches: [ "github-action-integration" ]
  pull_request:
    branches: [ "github-action-integration" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      working-directory: ./user-service
      run: npm ci
      
    - name: Run tests
      env:
        MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGODB_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}
      working-directory: ./user-service
      run: npm test
      