name: Node CI

on:
  push:
    branches: [ "github-action-integration" ]
  pull_request:
    branches: [ "github-action-integration" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./user-service

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGODB_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}
      run: |
        npm ci
        npm run build --if-present
        npm test
      working-directory: user-service